# Generated by Django 5.0.6 on 2024-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
