# Generated by Django 5.0.6 on 2024-05-24 11:57

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_comment", "0001_initial"),
        ("apps_user", "0003_user_posts_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comments_liked",
            field=models.ManyToManyField(
                related_name="commented_by", to="apps_comment.comment"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.user.models.user_directory_path
            ),
        ),
    ]
