# Generated by Django 5.0.6 on 2024-05-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps_post", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="'apps.post'",
        ),
    ]
